app/models/returns.py
from peewee import *
from app.database import db
from app.models.storeLocation import StoreLocation
from app.models.product import Product

class Returns(db.Model):

    return_id = PrimaryKeyField()
    store_id = ForeignKeyField(StoreLocation, backref="Returns")
    product_id = ForeignKeyField(Product, backref="Returns")
    return_date = DateField()
    return_reason = CharField()

    class Meta:
        database = db
        table_name = 'Returns'

app/routes/returns.py
from datetime import date
from flask import Blueprint, render_template, request, redirect, url_for
from app.services.returns_services import ReturnsService
from app.services.store_location_services import StoreLocationService
from app.services.product_services import ProductService

bp = Blueprint('returns', __name__)

@bp.route('/list/')
def returns_list():
    returns_service = ReturnsService()
    returns = returns_service.get_returns_list()
    return render_template('returns/returns_list.html', returns=returns)

@bp.route('/detail/<int:return_id>/')
def returns_detail(return_id):
    returns_service = ReturnsService()
    returns = returns_service.get_returns_by_id(return_id)

    if returns:
        return render_template('returns/returns_detail.html', returns=returns)
    else:
        return render_template('returns/returns_not_found.html')

@bp.route('/create/', methods=['GET', 'POST'])
def create_return():
    if request.method == 'POST':
        data = request.form.to_dict(flat=True)
        return_date = date.today().strftime("%Y-%m-%d")
        returns = ReturnsService().create_returns(data['product_id'], data['store_id'], return_date, data['return_reason'])

        return redirect(url_for('returns.returns_list'))

    all_stores = StoreLocationService().get_store_location_list()
    all_products = ProductService().get_product_list()
    return render_template('returns/create_return.html', stores = all_stores, products = all_products)

app/templates/returns/create_return.html
{% extends "base.html" %}

{% block title %}Create New Return{% endblock %}

{% block content %}
  <h1 class="text-2xl font-bold mb-4">Create New Return</h1>
  <form action="{{ url_for('returns.create_return') }}" method="post" class="w-full max-w-sm">
    <div class="mb-4">
      <label for="store" class="block text-gray-700 font-bold mb-2">Store:</label>
      <select name="store_id" id="store" class="form-select block w-full border rounded py-2 px-3">
        {% for store in stores %}
        <option value="{{ store.store_id }}">{{ store.store_name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="mb-4">
      <label for="product" class="block text-gray-700 font-bold mb-2">Product:</label>
      <select name="product_id" id="product" class="form-select block w-full border rounded py-2 px-3">
        {% for product in products %}
        <option value="{{ product.product_id }}">{{ product.product_name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="mb-4">
      <label for="return_reason" class="block text-gray-700 font-bold mb-2">Return Reason:</label>
      <textarea name="return_reason" id="return_reason" rows="4" class="form-textarea block w-full border rounded py-2 px-3"></textarea>
    </div>
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
      Create Return
    </button>
  </form>
{% endblock %}

app/templates/returns/returns_detail.html
{% extends "base.html" %} {% block title %}Return Details{% endblock %} {% block
content %}
<h1 class="text-2xl font-bold mb-4">Return Details</h1>
<div>
  <p><strong>Return ID:</strong> {{ returns.return_id }}</p>
  <p><strong>Store:</strong> {{ returns.store_id.store_name }}</p>
  <p><strong>Product:</strong> {{ returns.product_id.product_name }}</p>
  <p><strong>Return Date:</strong> {{ returns.return_date }}</p>
  <p><strong>Return Reason:</strong> {{ returns.return_reason }}</p>
</div>
<p class="mt-4">
  <a href="{{ url_for('returns.returns_list') }}" class="text-blue-500"
    >Back to Return List</a
  >
</p>
{% endblock %}

app/templates/returns/returns_list.html
{% extends "base.html" %} {% block title %}Returns List{% endblock %} {% block
content %}
<h1 class="text-2xl font-bold mb-4">Returns List</h1>
<div class="mb-4">
  <a
    href="{{ url_for('returns.create_return') }}"
    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
  >
    Create New Return
  </a>
</div>
<table class="w-full border-collapse border border-gray-500">
  <thead>
    <tr class="bg-gray-200">
      <th class="border border-gray-500 px-4 py-2">Return ID</th>
      <th class="border border-gray-500 px-4 py-2">Store</th>
      <th class="border border-gray-500 px-4 py-2">Product</th>
      <th class="border border-gray-500 px-4 py-2">Return Date</th>
      <th class="border border-gray-500 px-4 py-2">Return Reason</th>
    </tr>
  </thead>
  <tbody>
    {% for item in returns %}
    <tr>
      <td class="border border-gray-500 px-4 py-2">
        <a
          href="{{ url_for('returns.returns_detail', return_id=item.return_id) }}"
          >{{ item.return_id }}</a
        >
      </td>
      <td class="border border-gray-500 px-4 py-2">
        {{ item.store_id.store_name }}
      </td>
      <td class="border border-gray-500 px-4 py-2">
        {{ item.product_id.product_name }}
      </td>
      <td class="border border-gray-500 px-4 py-2">{{ item.return_date }}</td>
      <td class="border border-gray-500 px-4 py-2">{{ item.return_reason }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}