app/routes/product.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.services.product_services import ProductService

bp = Blueprint('product', __name__)

@bp.route('/list/')
def product_list():
    product_service = ProductService()
    products = product_service.get_product_list()
    return render_template('product/product_list.html', products=products)

@bp.route('/detail/<int:product_id>/')
def product_detail(product_id):
    product_service = ProductService()
    product = product_service.get_product_by_id(product_id)

    if product:
        return render_template('product/product_detail.html', product=product)
    else:
        return render_template('product/product_not_found.html')

@bp.route('/discontinue/<int:product_id>/', methods=['GET', 'POST'])
def discontinue_product(product_id):
    if request.method == 'POST':
        try:
            product_service = ProductService()
            result = product_service.discontinue_product(product_id)

            if result:
                return redirect(url_for('product.product_list'))
            else:
                return render_template('product/product_not_found.html')

        except ValueError:
            return render_template('invalid_product_id.html')

    return redirect(url_for('product.product_list'))

@bp.route('/outofstock/<int:product_id>/', methods=['GET', 'POST'])
def out_of_stock_product(product_id):
    if request.method == 'POST':
        try:
            product_service = ProductService()
            result = product_service.out_of_stock_product(product_id)

            if result:
                return redirect(url_for('product.product_list'))
            else:
                return render_template('product/product_not_found.html')

        except ValueError:
            return render_template('invalid_product_id.html')

    return redirect(url_for('product.product_list'))

@bp.route('/updateprice/', methods=['GET','POST'])
def update_product_price():

    if request.method == 'POST':
        data = request.form.to_dict(flat=True)
        product_cost = data['product_cost']
        product_id = data['product_id']

        updated_product = ProductService.update_price(product_id,product_cost)

        if updated_product:
            return redirect(url_for('product.product_list'))
        else:
            return "update failed"
        
    return render_template('product/update_price.html')

app/routes/reviews.py
from flask import Blueprint, request
from app.services.review_services import ReviewService
from flask import render_template

bp = Blueprint('reviews', __name__)

#Default reviews route, returns list of all product reviews
@bp.route('/list/', methods=['GET'])
def review_list():
    reviews = ReviewService.review_list()
    return render_template('/reviews/review_list.html', reviews=reviews)

#Returns list of product reviews by product_id
@bp.route('/id/', methods=['GET','POST'])
def get_product_reviews_by_id():

    reviews = []

    if request.method == 'POST':
        data = request.form.to_dict(flat=True)
        reviews = ReviewService.get_product_reviews_by_id(data['product_id'])
    
    return render_template('/reviews/review_by_id.html', reviews=reviews)

#Returns list of product reviews by product name
@bp.route('/name/', methods=['GET', 'POST'])
def get_product_reviews_by_name():

    reviews = []

    if request.method == 'POST':
        data = request.form.to_dict(flat=True)
        reviews = ReviewService.get_product_reviews_by_name(data['product_name'])
    
    return render_template('/reviews/review_by_name.html', reviews=reviews)

#Returns list of product reviews by user name
@bp.route('/user/', methods=['GET', 'POST'])
def get_product_reviews_by_user():
    reviews = []

    if request.method == 'POST':
        data = request.form.to_dict(flat=True)
        reviews = ReviewService.get_product_reviews_by_user(data['user_id'])
    
    return render_template('/reviews/review_by_user.html', reviews=reviews)

app/templates/reviews/review_by_id.html
{% extends "base.html" %}

{% block title %}
    Product Reviews
{% endblock %}

{% block content %}
    <h1 class="text-2xl font-bold mb-4">Product Reviews</h1>
    <!-- HTML form for entering the product ID -->
    <form method="post" action="{{ url_for('reviews.get_product_reviews_by_id') }}" class="mb-4">
        <div class="mb-2">
            <label for="product_id" class="block font-medium mb-1">Product ID:</label>
            <input type="text" name="product_id" id="product_id" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200">
        </div>
        <button type="submit" class="px-4 py-2 font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-200">Search</button>
    </form>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {% for review in reviews %}
        <div class="border border-gray-300 rounded p-4">
            <h2 class="text-xl mb-2">{{ review.user_id.user_name }}</h2>
            <p class="text-gray-800 mb-2">
                <strong>
                    <a href="{{ url_for('product.product_detail', product_id=review.product_id.product_id) }}" class="text-blue-500 hover:underline">
                        {{ review.product_id.product_name }}
                    </a>
                </strong>
            </p>
            <p class="text-gray-600 mb-2">{{ review.review_date }}</p>
            <p class="text-gray-800 mb-2">Rating: {{ review.product_rating }}/5</p>
            <p class="text-gray-800">{{ review.product_review }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/reviews/review_by_name.html
{% extends "base.html" %}

{% block title %}
    Product Reviews
{% endblock %}

{% block content %}
    <h1 class="text-2xl font-bold mb-4">Product Reviews</h1>
    <!-- HTML form for entering the product ID -->
    <form method="post" action="{{ url_for('reviews.get_product_reviews_by_name') }}" class="mb-4">
        <div class="mb-2">
            <label for="product_name" class="block font-medium mb-1">Product name:</label>
            <input type="text" name="product_name" id="product_name" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200">
        </div>
        <button type="submit" class="px-4 py-2 font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-200">Search</button>
    </form>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {% for review in reviews %}
        <div class="border border-gray-300 rounded p-4">
            <h2 class="text-xl mb-2">{{ review.user_id.user_name }}</h2>
            <p class="text-gray-800 mb-2">
                <strong>
                    <a href="{{ url_for('product.product_detail', product_id=review.product_id.product_id) }}" class="text-blue-500 hover:underline">
                        {{ review.product_id.product_name }}
                    </a>
                </strong>
            </p>
            <p class="text-gray-600 mb-2">{{ review.review_date }}</p>
            <p class="text-gray-800 mb-2">Rating: {{ review.product_rating }}/5</p>
            <p class="text-gray-800">{{ review.product_review }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/reviews/review_by_user.html
{% extends "base.html" %}

{% block title %}
    Product Reviews
{% endblock %}

{% block content %}
    <h1 class="text-2xl font-bold mb-4">Product Reviews</h1>
    <!-- HTML form for entering the user ID -->
    <form method="post" action="{{ url_for('reviews.get_product_reviews_by_user') }}" class="mb-4">
        <div class="mb-2">
            <label for="user_id" class="block font-medium mb-1">user ID:</label>
            <input type="text" name="user_id" id="user_id" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200">
        </div>
        <button type="submit" class="px-4 py-2 font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-200">Search</button>
    </form>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {% for review in reviews %}
        <div class="border border-gray-300 rounded p-4">
            <h2 class="text-xl mb-2">{{ review.user_id.user_name }}</h2>
            <p class="text-gray-800 mb-2">
                <strong>
                    <a href="{{ url_for('product.product_detail', product_id=review.product_id.product_id) }}" class="text-blue-500 hover:underline">
                        {{ review.product_id.product_name }}
                    </a>
                </strong>
            </p>
            <p class="text-gray-600 mb-2">{{ review.review_date }}</p>
            <p class="text-gray-800 mb-2">Rating: {{ review.product_rating }}/5</p>
            <p class="text-gray-800">{{ review.product_review }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/reviews/review_list.html
{% extends "base.html" %} {% block title %} Product Reviews {% endblock %} {%
block content %}
<h1 class="text-2xl font-bold mb-4">Product Reviews</h1>
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
  {% for review in reviews %}
  <div class="border border-gray-300 rounded p-4">
    <h2 class="text-xl mb-2">{{ review.user_id.user_name }}</h2>
    <p class="text-gray-800 mb-2">
      <strong>
        <a
          href="{{ url_for('product.product_detail', product_id=review.product_id.product_id) }}"
          class="text-blue-500 hover:underline"
        >
          {{ review.product_id.product_name }}
        </a>
      </strong>
    </p>
    <p class="text-gray-600 mb-2">{{ review.review_date }}</p>
    <p class="text-gray-800 mb-2">Rating: {{ review.product_rating }}/5</p>
    <p class="text-gray-800">{{ review.product_review }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}