app/models/inventory.py
from peewee import *
from app.database import db
from app.models.storeLocation import StoreLocation
from app.models.product import Product

class Inventory(db.Model):

    inventory_id = AutoField()
    store_id = ForeignKeyField(StoreLocation, backref='Inventory')
    product_id = ForeignKeyField(Product, backref='Inventory')
    product_quantity = IntegerField()

    class Meta:
        database = db
        table_name = 'Inventory'

app/routes/inventory.py
from flask import Blueprint, request, jsonify, render_template
from app.services.inventory_services import InventoryService
from app.services.store_location_services import StoreLocationService
from app.services.product_services import ProductService
from flask import redirect, url_for

bp = Blueprint('inventory', __name__)

#Route for display all current inventory objects in all stores
@bp.route('/list/', methods=['GET'])
def inventory_list():
    inventory = InventoryService().get_inventory_list()
    return render_template('inventory/inventory_list.html', inventory=inventory)

#Route to add a new product into inventory
@bp.route('/add/', methods=['GET','POST'])
def add_inventory():

    if request.method == 'POST':
        data = request.form.to_dict(flat=True)
        inventory = InventoryService().add_inventory(data['product_id'], data['store_id'], data['product_cost'], data['product_quantity'])
        return "success", 201
    
    all_stores = StoreLocationService().get_store_location_list()
    all_products = ProductService().get_product_list()
    return render_template('inventory/add_inventory.html', store_locations = all_stores, products = all_products)


#Route for searching for a product by name in any store
@bp.route('/search/name/', methods=['GET', 'POST'])
def search_by_product_name():

    product_list = []

    if request.method == 'POST':
        data = request.form.to_dict(flat=True)
        product_name = data['product_name']

        return redirect(url_for('inventory.display_search_name', product_name = product_name))

    return render_template('inventory/inv_search_name.html', product_list=product_list)


#Route for searching for a product by id in any store
@bp.route('/search/id/', methods=['GET','POST'])
def search_by_product_id():

    product_list = []

    if request.method == 'POST':
        data = request.form.to_dict(flat=True)
        product_id = data['product_id']

        return redirect(url_for('inventory.display_search_id', product_id = product_id))

    return render_template('inventory/inv_search_id.html', product_list=product_list)


#Route for searching for a product in a specific store
@bp.route('/search/store/', methods=['GET', 'POST'])
def search_by_product_store():

    product_list = []

    if request.method == 'POST':
        data = request.form.to_dict(flat=True)
        product_id = data['product_id']
        store_id = data['store_id']

        return redirect(url_for('inventory.display_search_store', product_id = product_id, store_id=store_id))

    return render_template('inventory/inv_search_store.html', product_list=product_list)

#Route to display results for search by name
@bp.route('/search/results/name', methods=['GET'])
def display_search_name():
    
    product_name = request.args.get('product_name')

    product_list = InventoryService.search_by_product_name(product_name)
    product_cost = product_list['cost']
    product_list = product_list['details']
    
    return render_template('inventory/inv_search_results.html', product_list=product_list, product_cost=product_cost)

#Route to display results for search by ID
@bp.route('/search/results/id', methods=['GET'])
def display_search_id():
    
    product_id = request.args.get('product_id')

    product_list = InventoryService.search_by_product_id(product_id)
    product_cost = product_list['cost']
    product_name = product_list['name']
    product_list = product_list['details']

    return render_template('inventory/inv_search_results.html', product_list=product_list, product_cost=product_cost, product_name=product_name)

#Route to display results for search by store and by ID
@bp.route('/search/results/store', methods=['GET'])
def display_search_store():
    
    product_id = request.args.get('product_id')
    store_id = request.args.get('store_id')

    product_list = InventoryService.search_by_product_store(product_id, store_id)
    product_cost = product_list['cost']
    product_name = product_list['name']
    product_list = product_list['details']

    return render_template('inventory/inv_search_results.html', product_list=product_list, product_cost=product_cost, product_name=product_name)

app/templates/inventory/add_inventory.html
{% extends "base.html" %}

{% block title %}
    Add Shipment
{% endblock %}

{% block content %}
    <h1 class="text-2xl font-bold mb-4">Add Product to Inventory</h1>
    <form method="POST" action="{{ url_for('inventory.add_inventory') }}" class="max-w-md mx-auto">
        <div class="mb-4">
            <label for="product_id" class="block font-medium mb-1">Product</label>
            <select name="product_id" id="product_id" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200">
                {% for product in products %}
                    <option value="{{ product.product_id }}">{{ product.product_name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-4">
            <label for="store_location" class="block font-medium mb-1">Store Location</label>
            <select name="store_id" id="store_id" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200">
                {% for location in store_locations %}
                    <option value="{{ location.store_id }}">{{ location.store_name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-4">
            <label for="product_cost" class="block font-medium mb-1">Product Cost</label>
            <select name="product_cost" id="product_cost" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200">
                {% for product in products %}
                    <option value="{{ product.product_cost }}">{{ product.product_cost }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-4">
            <label for="product_quantity" class="block font-medium mb-1">Shipment Quantity</label>
            <input type="number" name="product_quantity" id="product_quantity" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200" required>
        </div>

        <div class="mb-4">
            <input type="submit" value="Add Product" class="w-full px-4 py-2 font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-200">
        </div>
    </form>

{% endblock %}

app/templates/inventory/inv_search_id.html
{% extends "base.html" %}

{% block title %}
    Product Inventory
{% endblock %}

{% block content %}
    <h1 class="text-2xl font-bold mb-4">Product Inventory</h1>
    <form method="POST" action="{{ url_for('inventory.search_by_product_id') }}" class="max-w-md mx-auto mb-4">
        <div class="mb-4">
            <label for="product_id" class="block font-medium mb-1">Product ID</label>
            <input type="text" name="product_id" id="product_id" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200" required>
        </div>
        <div class="mb-4">
            <input type="submit" value="Search" class="w-full px-4 py-2 font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-200">
        </div>
    </form>


{% endblock %}

app/templates/inventory/inv_search_name.html
{% extends "base.html" %}

{% block title %}
    Product Inventory
{% endblock %}

{% block content %}
    <h1 class="text-2xl font-bold mb-4">Product Inventory</h1>
    <form method="POST" action="{{ url_for('inventory.search_by_product_name') }}" class="max-w-md mx-auto mb-4">
        <div class="mb-4">
            <label for="product_name" class="block font-medium mb-1">Product Name</label>
            <input type="text" name="product_name" id="product_name" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200" required>
        </div>
        <div class="mb-4">
            <input type="submit" value="Search" class="w-full px-4 py-2 font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-200">
        </div>
    </form>


{% endblock %}

app/templates/inventory/inv_search_results.html
{% extends "base.html" %}

{% block title %}
    Product Inventory
{% endblock %}

{% block content %}


<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    {% for product in product_list %}
        <div class="border border-gray-300 rounded p-4">
            <h2 class="text-xl mb-2">{{ product_name }}</h2>
            <p class="text-gray-800 mb-2">
                <strong>Product ID:</strong> {{ product.product_id }}
            </p>
            <p class="text-gray-800 mb-2">
                <strong>Store ID:</strong> {{ product.store_id }}
            </p>
            <p class="text-gray-800 mb-2">
                <strong>Product Cost:</strong> ${{ product_cost }}
            </p>
            <p class="text-gray-800">
                <strong>Product Quantity:</strong> {{ product.product_quantity }}
            </p>
        </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/inventory/inv_search_store.html
{% extends "base.html" %}

{% block title %}
    Product Inventory
{% endblock %}

{% block content %}
    <h1 class="text-2xl font-bold mb-4">Product Inventory</h1>
    <form method="POST" action="{{ url_for('inventory.search_by_product_store') }}" class="max-w-md mx-auto mb-4">
        <div class="mb-4">
            <label for="product_id" class="block font-medium mb-1">Product ID</label>
            <input type="text" name="product_id" id="product_id" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200" required>
        </div>
        <div class="mb-4">
            <label for="store_id" class="block font-medium mb-1">Store ID</label>
            <input type="text" name="store_id" id="store_id" class="w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200" required>
        </div>
        <div class="mb-4">
            <input type="submit" value="Search" class="w-full px-4 py-2 font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-200">
        </div>
    </form>


{% endblock %}

app/templates/inventory/inventory_list.html
{% extends "base.html" %} {% block title %} Inventory List {% endblock %} {% block
content %}
<h1 class="text-2xl font-bold mb-4">Inventory List</h1>
<table class="w-full border-collapse border border-gray-500">
  <thead>
    <tr class="bg-gray-200">
      <th class="border border-gray-500 px-4 py-2">Inventory ID</th>
      <th class="border border-gray-500 px-4 py-2">Store</th>
      <th class="border border-gray-500 px-4 py-2">Product</th>
      <th class="border border-gray-500 px-4 py-2">Product Quantity</th>
    </tr>
  </thead>
  <tbody>
    {% for item in inventory %}
    <tr>
      <td class="border border-gray-500 px-4 py-2">{{ item.inventory_id }}</td>
      <td class="border border-gray-500 px-4 py-2">{{ item.store_id.store_name }}</td>
      <td class="border border-gray-500 px-4 py-2">
        {{ item.product_id.product_name }}
      </td>
      <td class="border border-gray-500 px-4 py-2">
        {{ item.product_quantity }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

app/templates/inventory/table_template.html
<!DOCTYPE html>
<html>
<head>
    <title>JSON Data</title>
    <style>
        /* Add CSS styles for the bordered table */
        table {
            border-collapse: collapse;
            border: 1px solid #ddd;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>JSON Data Table</h1>
    <table>
        <tr>
            <th>Key</th>
            <th>Value</th>
        </tr>
        {% for data in json_list %}
        {% for key, value in data.items() %}
        <tr>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
        </tr>
        {% endfor %}
        {% if not loop.last %}
        <tr></tr> <!-- Empty row between dictionaries -->
        {% endif %}
        {% endfor %}
    </table>
</body>
</html>